functionsDirectory = "C:\\Users\\prosm\\Desktop\\NK\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []

[build]
publish = "C:\\Users\\prosm\\Desktop\\NK"
publishOrigin = "config"
functions = "C:\\Users\\prosm\\Desktop\\NK\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/skatte-kalkulator.html"
to = "/skatte-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/drivstoffkalkulator.html"
to = "/drivstoff-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/feriepengerkalkulator.html"
to = "/feriepenger-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/overtidkalkulator.html"
to = "/overtids-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/energisparingkalkulator.html"
to = "/energisparing-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/flyttekostnadkalkulator.html"
to = "/flyttekostnad-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/malingskalkulator.html"
to = "/malings-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reisebudsjettkalkulator.html"
to = "/reisebudsjett-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/bryllupsbudsjettkalkulator.html"
to = "/bryllupsbudsjett-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/tv-storrelsekalkulator.html"
to = "/tv-storrelse-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/energisparing.html"
to = "/energisparing-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/overtidskalkulator.html"
to = "/overtids-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/skattekalkulator.html"
to = "/skatte-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/bryllupskostnadkalkulator.html"
to = "/bryllupsbudsjett-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/om-oss.html"
to = "/om-oss"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/kontakt.html"
to = "/kontakt"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/faq.html"
to = "/faq"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/personvern.html"
to = "/personvern"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/index.html"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/skattekalkulator"
to = "/skatte-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/drivstoffkalkulator"
to = "/drivstoff-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/feriepengerkalkulator"
to = "/feriepenger-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/overtidkalkulator"
to = "/overtids-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/tvstorrelsekalkulator"
to = "/tv-storrelse-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/tv-storrelsekalkulator"
to = "/tv-storrelse-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/energisparingkalkulator"
to = "/energisparing-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/flyttekostnadkalkulator"
to = "/flyttekostnad-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/malingskalkulator"
to = "/malings-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reisebudsjettkalkulator"
to = "/reisebudsjett-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/bryllupsbudsjettkalkulator"
to = "/bryllupsbudsjett-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/tv-storrelse"
to = "/tv-storrelse-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/energisparing"
to = "/energisparing-kalkulator/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/omoss"
to = "/om-oss"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/kontakt"
to = "/kontakt"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/faq"
to = "/faq"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/personvern"
to = "/personvern"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]